Q. SUPONDO QUE TENHAMOS O SEGUINTE CSV, PRESENTE EM helpers.txt, OBTER UM CONJUNTO DAS 4 PRIMEIRAS PESSOAS, SENDO INFORMADOS O ID E ESTADO, ORDENADO PELO NOME DO ESTADO

1;JOÃO;SÃO PAULO;21
2;MARIA;RIO GRANDE DO SUL;30
3;PEDRO;BAHIA;18
4;ANTÔNIO;SANTA CATARINA;40
5;MARCOS;PARANÁ;50
6;VICTÓRIA;RIO DE JANEIRO;22

R. head -n4 helpers.txt | cut -d";" -f1,3 | sort -t ";" -k1