# A PARTIR DE UM CSV DE CLIENTES, OBTER UM RETORNO DA SEGUINTE FORMA:

# OBTER UM CONJUNTO DAS 4 PRIMEIRAS PESSOAS, EXIBINDO O ID E O ESTADO, ORDENADOS PELO NOME DO ESTADO;

# É PERMITIDO INSERÇÃO DE COMENTÁRIOS, DESDE QUE INICIEM POR CERQUILHA (#);

cat Client.CSV | grep -vE "^#" | head -n4 | tr -s "[:blank:]" | cut -d";" -f1,3 | sort -t ";" -k2