/**
 * NÃO RETORNA UM ERRO AO REALIZAR UMA DIVISÃO POR ZERO.
 */
console.log(10 / 0);

/**
 * CALCULA NORMALMENTE, EMBORA SEJA INFORMADA UMA STRING.
 */
console.log("10" / 2);

/**
 * RETORNA NOT A NUMBER, AO INVÉS DE REPETIR A STRING N VEZES.
 */
console.log("Show" * 2);

/**
 * GERA UMA IMPRECISÃO NA SAÍDA, ATENTAR PARA ISSO.
 */
console.log(0.1 + 0.2);

/**
 * NÃO É POSSÍVEL PASSAR UM NÚMERO IMEDIATAMENTE SEGUIDO DO MÉTODO, DEVEM SER USADOS PARENTESES PARA ISSO,
 * OU PASSAR O VALOR ATRAVÉS DE UMA VARIÁVEL. 
 */
console.log((10).toString());

/**
 * NÃO HÁ PROBLEMAS EM PASSAR UM NÚMERO DIRETAMENTE PARA O MÉTODO, MAS
 * DEVEM SER USADOS PARENTESES.
 */
console.log((10.274).toFixed(2));